// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import (
	domain "meli-items-w2/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// ItemUsecase is an autogenerated mock type for the ItemUsecase type
type ItemUsecase struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: item
func (_m *ItemUsecase) AddItem(item domain.Item) *domain.Item {
	ret := _m.Called(item)

	var r0 *domain.Item
	if rf, ok := ret.Get(0).(func(domain.Item) *domain.Item); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	return r0
}

// DeleteItem provides a mock function with given fields: id
func (_m *ItemUsecase) DeleteItem(id int) *domain.Item {
	ret := _m.Called(id)

	var r0 *domain.Item
	if rf, ok := ret.Get(0).(func(int) *domain.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	return r0
}

// GetItemById provides a mock function with given fields: id
func (_m *ItemUsecase) GetItemById(id int) *domain.Item {
	ret := _m.Called(id)

	var r0 *domain.Item
	if rf, ok := ret.Get(0).(func(int) *domain.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	return r0
}

// ListItem provides a mock function with given fields: status
func (_m *ItemUsecase) ListItem(status string) []domain.Item {
	ret := _m.Called(status)

	var r0 []domain.Item
	if rf, ok := ret.Get(0).(func(string) []domain.Item); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	return r0
}

// UpdateItem provides a mock function with given fields: item, id
func (_m *ItemUsecase) UpdateItem(item domain.Item, id int) *domain.Item {
	ret := _m.Called(item, id)

	var r0 *domain.Item
	if rf, ok := ret.Get(0).(func(domain.Item, int) *domain.Item); ok {
		r0 = rf(item, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	return r0
}

type mockConstructorTestingTNewItemUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemUsecase creates a new instance of ItemUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemUsecase(t mockConstructorTestingTNewItemUsecase) *ItemUsecase {
	mock := &ItemUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
